name: rocketsms
services:
  appserver:
    type: php:7.4
    composer_version: 2
    xdebug: debug,develop
    environment:
      PHP_IDE_CONFIG: serverName=rocketsms.lndo.site
      XDEBUG_SESSION_START: PHPSTORM
